name: AntiCheat
version: ${project.version}
main: chanhne.AntiCheat.AntiCheatPlugin
folia-supported: true
api-version: '1.21'
description: Tự động phát hiện và xóa các item bất hợp pháp trong Inventory. Support paper/folia
author: Chanhne
depend: [ChanhOffPlugin]        # bắt buộc phải có ChanhOffPlugin

commands:
  illegal:
    description: Lệnh quản lý AntiCheat
    aliases: [ill]
    usage: /<command> <reload> [player]
    permission: anticheat.admin

permissions:
  anticheat.admin:
    description: Quyền quản trị plugin
    default: op